name: Windows Build
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            cuda: "11.3.1"
            compiler: "Ninja"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: get latest CMake and ninja
        # Using 'latest' branch, the most recent CMake and ninja are installed.
        uses: lukka/get-cmake@latest

      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          method: 'network'
          cuda: '11.3.1'
          sub-packages: '["nvcc", "cupti", "visual_profiler", "nvprof", "cublas", "cublas_dev", "nvjpeg", "nvjpeg_dev", "npp", "npp_dev", "cufft", "cufft_dev", "nvrtc", "nvrtc_dev", "curand", "curand_dev", "cusolver", "cusolver_dev", "cusparse", "cusparse_dev", "nvml_dev", "cudart", "visual_studio_integration", "thrust"]'

      - name: install cudnn
        shell: pwsh
        run: .\scripts\install_cuda.ps1

      - name: install OpenCV
        shell: pwsh
        run: |
          choco install opencv
          echo "OPENCV_DIR=c:\tools\opencv\build" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "c:\tools\opencv\build\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "c:\tools\opencv\build\x64\vc15\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: install OpenBlas
        shell: pwsh
        run: |
          Invoke-WebRequest https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21-x64.zip -OutFile OpenBLAS.zip | Out-Null
          Expand-Archive -Path OpenBLAS.zip -DestinationPath "d:\utils\OpenBLAS"
          echo "OpenBLAS_HOME=d:\utils\OpenBLAS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      #- name: install MKL
      #  shell: pwsh
      #  run: |
      #    Invoke-WebRequest https://registrationcenter-download.intel.com/akdlm/irc_nas/18723/w_onemkl_p_2022.1.0.192_offline.exe -OutFile setup.exe | Out-Null
      #    Start-Process -Wait -FilePath .\setup.exe -ArgumentList "-s -a --silent --eula accept"

      - name: check Env
        shell: pwsh
        run: |
          Write-Output "---- NVCC Output ----"
          nvcc -V
          Write-Output "---------------------"
          Write-Output "CUDA PATH: $($env:CUDA_PATH)"
          Write-Output "Path: $($env:Path)"
          Write-Output "OpenCV: $($env:OPENCV_DIR)"
          Write-Output "OpenBLAS: $($env:OpenBLAS)"

      - name: Configure by CMake
        id: configure
        shell: pwsh
        run: |
          mkdir -p .\incubator-mxnet\build
          cd .\incubator-mxnet\build
          cmd /K '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && pwsh.exe'
          $CXXFLAGS='/FS /MD /O2 /Ob2'
          cmake -G "${{ matrix.compiler }}"`
                -DCMAKE_CXX_COMPILER=cl`
                -DCMAKE_C_COMPILER=cl`
                -DUSE_BLAS=open`
                -DUSE_MKL_IF_AVAILABLE=OFF`
                -DUSE_CUDA=ON `
                -DUSE_CUDNN=ON `
                -DENABLE_CUDA_RTC=ON `
                -DUSE_OPENCV=ON  `
                -DUSE_OPENMP=ON `
                -DUSE_LAPACK=ON `
                -DCMAKE_BUILD_TYPE:STRING=Release`
                -DCUDAToolkit_ROOT:PATH="$env:CUDA_PATH"`
                -DMXNET_CUDA_ARCH:STRING="8.6" `
                ..

      - name: CMake Configure Error Processing
        if: ${{ (failure() && steps.configure.outcome == 'failure') || success() }}
        working-directory: ${{ env.build_dir }}
        shell: pwsh
        run: |
          pwd
          echo "---- CMakeFiles/CMakeOutput.log"
          cat .\incubator-mxnet\build\CMakeFiles\CMakeOutput.log
          echo "----"
          echo "---- CMakeFiles/CMakeError.log"
          cat .\incubator-mxnet\build\CMakeFiles\CMakeError.log
          echo "----"

      - name: Build
        id: build
        shell: pwsh
        run: |
          cd .\incubator-mxnet\build
          cmd /K '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && pwsh.exe'
          cmake --build . --config Release
          cd ..
          Compress-Archive -Path .\build\ -DestinationPath libraries.zip

      - name: CMake Build Error Processing
        if: ${{ (failure() && steps.build.outcome == 'failure') || success() }}
        working-directory: ${{ env.build_dir }}
        shell: pwsh
        run: |
          pwd
          echo "---- CMakeFiles/CMakeOutput.log"
          cat .\incubator-mxnet\build\CMakeFiles\CMakeOutput.log
          echo "----"
          echo "---- CMakeFiles/CMakeError.log"
          cat .\incubator-mxnet\build\CMakeFiles\CMakeError.log
          echo "----"

      - name: Archive production artifacts build
        uses: actions/upload-artifact@v3
        with:
          name: mxnet-libraries
          path: |
            .\incubator-mxnet\libraries.zip

      - name: Python wheel build
        shell: pwsh
        run: |
          pip install wheel
          cd .\incubator-mxnet
          python .\python\setup.py bdist_wheel --plat-name win_amd64

      #- name: Archive production artifacts wheel
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: mxnet-libraries
      #    path: |
      #      .\incubator-mxnet\dist
